### ISSUE TITLE
Bug: Tags within a footnote cannot be followed by doublepoint ":"

### ISSUE THREAD

**Issue by Gewerd-Strauss** [obsidian-html/obsidian-html#527]
Hello,

this is one of a series of bugs that occured to me when usign ObsidianHTML.

## Input

```md
---
creation date: 2022-06-26 13:23
IntakeFrequency: 
modification date: 2023-01-05 11:53
tags: programming 
---

# ObsidianHTML_FootnotewithTags_andDoublePoint

Text[^1]

[^1]: NOte is this: a #tag: with a doublepoint

```
---
## Output 
This doesn't even finish executing, and does so in a destructive manner:
The notation `obshtml_XXXX_t` suggests to me that this is a temporary intermediate step at which the script finishes.

The resulting output (hunted down in Appdata/Local/temp/obshtml_XXXX_t/md/index.md):

```md
---
IntakeFrequency: null
creation date: 2022-06-26 13:23
modification date: 2023-01-05 11:53
tags:
- 'tag:'
- programming
- 'tag:'
---

# ObsidianHTML_FootnotewithTags_andDoublePoint   
   
Text[^1]   
   
[^1]: NOte is this: a `{_obsidian_pattern_tag_tag:}` with a doublepoint
```

---
## The Script used for executing pandoc:

R-Script `build.R` executed:

```R
getwd()
setwd("C:\\Users\\Claudius Main\\Desktop\\TempTemporal\\ObsidianHTML_FootnotewithTags_andDoublePoint")
getwd()

rmarkdown::render("index.rmd","html_document")
```

---

The complete, verbose log can be found in the log.txt

It should also be noted that the "tag" `tag:` is added to the frontmatter `tags`-field twice. Not sure why, won't be a problem I think, but still weird. 
Separating the tag from the doublepoint in the note before executing Obsidianhtml will resolve this issue, but it's an intrusive bug nonetheless.

---

I hope this information is sufficient.

Thank you,
Sincerely,
~Gw

---

Attachments:

[log.txt](https://github.com/obsidian-html/obsidian-html/files/10351582/log.txt)

**Comment by dwrolvink** [comment]
Can't say I have the same experience as you. Using your test code it finishes executing just fine, though the tag is not shown in the html output, just the `%%%codeline-placeholder-0%%%` placeholder.

I did notice that Obsidian automatically breaks off the tag if a `:` follows it, so I implemented that.

I guess I never tested inline tags in a footnote before, that was not being replaced properly before the placeholder values were removed, so I added an extra replace step, and now your example works perfectly for me.

Give it a try and let me know how it goes.

**Comment by dwrolvink** [comment]
That log output though :laughing: we need to do something about that spammy exclude
Or did you have verbose logging on?

**Comment by Gewerd-Strauss** [comment]
> That log output though 😆 we need to do something about that spammy exclude
> Or did you have verbose logging on?

yes, this was intentionally done with `-v` because the nonverbose version was... artfully uninformative. However, I now agree that I should have provided both. I can do so if you want/need it.


----


> Can't say I have the same experience as you. Using your test code it finishes executing just fine, though the tag is not shown in the html output, just the `%%%codeline-placeholder-0%%%` placeholder.

This

```md

Text[^1]

[^1]: NOte is this: a #tag: with a doublepoint
```
will still not finish out completely - as in, it will not run to the point of giving me the location of my md-file (log at end, non-verbose).

I can dig it out of the output folder under `Appdata/Local/Temp/`:

```
---
IntakeFrequency: null
creation date: 2022-06-26 13:23
modification date: 2023-01-05 11:53
tags:
- programming
- 'tag:'
- tag
---
   
# ObsidianHTML_FootnotewithTags_andDoublePoint   
   
Text[^1]   
![](001%20assets/ObsidianHTML_FootnotewithTags_andDoublePoint.png)   
[^1]: NOte is this: a `{_obsidian_pattern_tag_tag}`: with a doublepoint
```
Which suggests the error itself is fixed.

However, it also does not finish to the point of completion where it will provide the paths to the outputted md- and html paths (cf. output below, non-verbose). The index note, as well as all sources _are_ located at the respective folder (rmd added manually for testing purposes)
![grafik](https://user-images.githubusercontent.com/80548781/210852935-63879539-afa1-45ce-b723-4166397d2553.png)


Whatever the reason, the fact that the output paths are not provided to the user suggests something is going wrong, because that is _supposed_ to happen, right? (Not to mention that my own buildscript  that wraps around ObsidianHTML relies on that information being fed back to the cmd, so please don't get rid of it :P)


---

```
ObsidianHTML Version: 3.3.1

---
Issued Command:
---
obsidianhtml run     -f "D:\Dokumente neu\Obsidian NoteTaking\The Universe\300 Personal\311 Programming\ObsidianHTML_FootnotewithTags_andDoublePoint.md"     -i "D:\Dokumente neu\000 AAA Dokumente\000 AAA HSRW\General\AHK scripts\Projects\Finished\ObsidianScripts\INI-Files\ObsidianHTML_Config.yml"
---

Command Line output below:
INFO: Config var was set. (provided by user through commandline)
	obsidian_entrypoint_path_str: D:/Dokumente neu/Obsidian NoteTaking/The Universe/300 Personal/311 Programming/ObsidianHTML_FootnotewithTags_andDoublePoint.md
INFO: Config var was set. (deduced)
	obsidian_folder_path_str: D:/Dokumente neu/Obsidian NoteTaking/The Universe
INFO: Creating tempdir
INFO: Created temporary directory C:/Users/Claudius Main/AppData/Local/Temp/obshtml_mtxmlc4s
INFO: Internal config var was set. (provided by user through commandline):
	[internal] output_folder_path: C:/Users/Claudius Main/AppData/Local/Temp/obshtml_mtxmlc4s 
INFO: Created empty output folder path C:\Users\Claudius Main\AppData\Local\Temp\obshtml_mtxmlc4s\md
INFO: Config var was set. (default behavior)
	md_folder_path_str: C:/Users/Claudius Main/AppData/Local/Temp/obshtml_mtxmlc4s/md
INFO: Config var was set. (default behavior)
	md_entrypoint_path_str: C:/Users/Claudius Main/AppData/Local/Temp/obshtml_mtxmlc4s/md/index.md
INFO: Created empty output folder path C:\Users\Claudius Main\AppData\Local\Temp\obshtml_mtxmlc4s\html
INFO: Config var was set. (default behavior)
	html_output_folder_path_str: C:/Users/Claudius Main/AppData/Local/Temp/obshtml_mtxmlc4s/html
DEPRECATION WARNING: The setting obsidian_folder_path_str is deprecated. See https://obsidian-html.github.io/Configurations/Deprecated%20Configurations/Deprecated%20Configurations.html for more information.
DEPRECATION WARNING: The setting exclude_subfolders is deprecated. See https://obsidian-html.github.io/Configurations/Deprecated%20Configurations/Deprecated%20Configurations.html for more information.
DEPRECATION WARNING: The setting toggles/features/styling/add_toc is deprecated. See https://obsidian-html.github.io/Configurations/Deprecated%20Configurations/Deprecated%20Configurations.html for more information.
DEPRECATION WARNING: The setting toggles/features/styling/toc_pane is deprecated. See https://obsidian-html.github.io/Configurations/Deprecated%20Configurations/Deprecated%20Configurations.html for more information.
DEPRECATION WARNING: The setting toggles/features/styling/flip_panes is deprecated. See https://obsidian-html.github.io/Configurations/Deprecated%20Configurations/Deprecated%20Configurations.html for more information.
> COPYING VAULT D:\Dokumente neu\Obsidian NoteTaking\The Universe TO C:\Users\CLAUDI~1\AppData\Local\Temp\tmpyuuc6egf
Paths that will be ignored: []

```

**Comment by dwrolvink** [comment]
So this command with the exact same input, just the : being removed will result in normal output?
That is very weird to me because the copying vault step comes before any processing step, so the contents of the vault files should be a moot point at that stage.

Could you remove the current output folder, run again, and check whether the output is there again?

I'm thinking that this is either a bug with the vault copy, though that seems unlikely with what you're telling me. Or it is just the output not being shown for some esoteric reason. I guess I'll have to get my windows laptop out of its box to test this myself on Windows.

Could you share the contents of `ObsidianHTML_Config.yml`?


```
> COPYING VAULT D:\Dokumente neu\Obsidian NoteTaking\The Universe TO C:\Users\CLAUDI~1\AppData\Local\Temp\tmpyuuc6egf
```
That is curious btw, it shows a shortened name (`CLAUDI~1`), whereas I am using posix strings everywhere, so I am not sure whether that works well with Windows when some source is shortening paths willy nilly.

What's up with the index.html being outputted in the same folder as the markdown files by the way?

**Comment by Gewerd-Strauss** [comment]
> So this command with the exact same input, just the : being removed will result in normal output?

Yes. For clarification:


```md
---
creation date: 2022-06-26 13:23
IntakeFrequency: 
modification date: 2023-01-06 11:11
tags: programming 
---

# ObsidianHTML_FootnotewithTags_andDoublePoint

Text[^1]  
![[ObsidianHTML_FootnotewithTags_andDoublePoint.png]]

[^1]: NOte is this: a #tag : with a doublepoint
```

will output to 

```md

---
IntakeFrequency: null
creation date: 2022-06-26 13:23
modification date: 2023-01-06 11:11
tags:
- tag
- programming
- tag
---
   
# ObsidianHTML_FootnotewithTags_andDoublePoint   
   
Text[^1]     
![](001%20assets/ObsidianHTML_FootnotewithTags_andDoublePoint.png)   
   
[^1]: NOte is this: a `{_obsidian_pattern_tag_tag}` : with a doublepoint
```

But setting the double point back to touch the tag in the footnote will result in

```md
---
IntakeFrequency: null
creation date: 2022-06-26 13:23
modification date: 2023-01-06 12:03
tags:
- programming
- 'tag:'
- tag
---
   
# ObsidianHTML_FootnotewithTags_andDoublePoint   
   
Text[^1]     
![](001%20assets/ObsidianHTML_FootnotewithTags_andDoublePoint.png)   
   
[^1]: NOte is this: a `{_obsidian_pattern_tag_tag}`: with a doublepoint
```

Which then errors out to the point of not supplying the output path, seen by the log:
[Executionlog.txt](https://github.com/obsidian-html/obsidian-html/files/10359815/Executionlog.txt)

To be precise, the "Your files are at this location: (..../md/) & (..../html/)" info is not printed. However, my script relies on that to continue, as it needs to find the output path to actu upon those files.

> 
> Could you remove the current output folder, run again, and check whether the output is there again?
> 
> I'm thinking that this is either a bug with the vault copy, though that seems unlikely with what you're telling me. Or it is just the output not being shown for some esoteric reason. I guess I'll have to get my windows laptop out of its box to test this myself on Windows.

I am not sure which you mean by `current output folder`. These ones: C`:/Users/Claudius Main/AppData/Local/Temp/obshtml_XXXXXXX`?

If so, they get cleaned up by my script  at the end.

> 
> Could you share the contents of `ObsidianHTML_Config.yml`?
> 

```yml
# Number of links a note can be removed from the entrypoint note
# -1 for no max depth
# 0 means only the entrypoint note is processed
# 1 means only direct children are processed (and the entrypoint of course)
# and so forth. NOTE: DOES NOT APPLY TO INCLUSIONS!
max_note_depth: 15

```

Side question: I know `max_note_depth` does not apply to inclusions, but are there any plans expanding it/adding a corresponding yaml-key for doing so? 


> ```
> > COPYING VAULT D:\Dokumente neu\Obsidian NoteTaking\The Universe TO C:\Users\CLAUDI~1\AppData\Local\Temp\tmpyuuc6egf
> ```
> 
> That is curious btw, it shows a shortened name (`CLAUDI~1`), whereas I am using posix strings everywhere, so I am not sure whether that works well with Windows when some source is shortening paths willy nilly.

I sadly cannot help you on that, I am not that familiar with windows in that regard. My computer name has a space, that may be the reason it gets abbreviated in that position. But that's also unlikely cuz it doesn't seem to happen for all spaces, so idk. SO far, it has never been an issue however.



> 
> What's up with the index.html being outputted in the same folder as the markdown files by the way?

Sorry, that was me not mentioning that when doing this

> The index note, [...] folder (rmd added manually for testing purposes)

I tested rendering by manually creating the rmd-file, then knitting it to html. Normally, this is done _after_ the `index.md`-file is moved to the Obsidian-Knittr-Output folder: `C:\Users\Claudius Main\Desktop\TempTemporal\<Notename>`
